apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: user-events
spec:
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 750m
      memory: 1Gi