apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-ms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: users-ms
  template:
    metadata:
      labels:
        component: users-ms
    spec:
      containers:
      - name: users-ms
        image: europe-west3-docker.pkg.dev/exploringmicroservices/exploringmicroservices/users-ms:latest
        ports:
        - containerPort: 3000
        env:
          - name: POSTGRES_DB
            value: users
          - name: POSTGRES_USER
            value: root
          - name: POSTGRES_PASSWORD
            value: root
          - name: POSTGRES_HOST
            value: users-ms-db
          - name: POSTGRES_PORT
            value: "5432"
      - name: users-ms-db
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_DB
            value: users
          - name: POSTGRES_USER
            value: root
          - name: POSTGRES_PASSWORD
            value: root
            
      imagePullSecrets:
      - name: k8s-gcloud

        
